version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g "%env(Lambda_function_name)%".zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name "%env(Lambda_function_name)%" --zip-file fileb://"%env(Lambda_function_name)%".zip
      - echo "DONE!!"
  pre_build:
    commands:
      - echo "Updating lambda Function..."
      - aws cloudformation update-stack --stack-name "%env(CFT_name)%" --tags Key=Project,Value=InstaGo Key=Owner,Value=MonishParekh Key=Environment,Value=Production Key=Application,Value=InstaGo Key=Name,Value="%env(Lambda_function_name)%" --template-body file://"%env(Lambda_function_name)%".yml --capabilities CAPABILITY_NAMED_IAM
      - echo "DONE!!"