version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  pre_build:
    commands:
      - chmod +x run.sh
      - chmod +x variables.json
      
  build:
    commands:
      - echo "Updating code update..."
      - ./run.sh
      - echo "DONE!!"
