version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo run run.sh file
      - sh run.sh
      - echo "Zipping deployment package..."
      - zip -g ${Lambda_function_name} lambda_function.py
  post_build:
    commands:
      - echo "Updating code update..."
      - aws lambda update-function-code --function-name ${Lambda_function_name} --zip-file fileb://${Lambda_function_name}.zip
      - echo "DONE!!"
  pre_build:
    commands:
      - echo "Updating lambda Function..."
      - aws cloudformation update-stack --stack-name ${CFT_name} --tags Key=Project,Value=InstaGo Key=Owner,Value=MonishParekh Key=Environment,Value=Production Key=Application,Value=InstaGo Key=Name,Value=${Lambda_function_name} --template-body file://${Lambda_function_name}.yml --capabilities CAPABILITY_NAMED_IAM
      - echo "DONE!!"