version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "upload zip package to s3 bucket...."
      - aws s3 cp *.zip s3://github-actions-1-dmo/lambda_2/
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws cloudformation update-stack --stack-name InstaGO-prod-L2T-lead-meeting-invoke-LambdaFunction --tags Key=Project,Value=InstaGo Key=Owner,Value=MonishParekh Key=Environment,Value=Production Key=Application,Value=InstaGo Key=Name,Value=InstaGO_prod_L2T_lead_meeting_invoke --template-body file://InstaGO_prod_L2T_lead_meeting_invoke.yml --capabilities CAPABILITY_NAMED_IAM
      - echo "DONE!!Thanks!!"
