version: 0.2

env:
  variables:
    LAMBDA_NAME: ""
    LAMBDA_CFT_NAME: ""
    LAMBDA_YML_NAME: ""
    LAMBDA_ZIP_NAME: ""

exported-variables:
  - myenvvars.env
  
phases:
  pre_build:
    commands:
      - chmod +x run.sh
      - source ./run.sh

  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  pre_build:
    commands:
      - echo "Zipping deployment package..."
      - ls -l
      - zip -r $LAMBDA_NAME.zip lambda_function.py
      - ls -l

  build:
    commands:
      - echo "Updating code update..."
      - aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://$LAMBDA_NAME.zip
      - echo "DONE!!"

  # post_build:
    # commands:
      # - echo "Updating lambda Function..."
      # - aws cloudformation update-stack --stack-name "$LAMBDA_CFT_NAME" --tags Key=Project,Value=InstaGo Key=Owner,Value=MonishParekh Key=Environment,Value=Production Key=Application,Value=InstaGo Key=Name,Value="$LAMBDA_NAME" --template-body file://"$LAMBDA_NAME".yml --capabilities CAPABILITY_NAMED_IAM
      # - echo "DONE!!"